spring:
  application:
    name: admin-shiro
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://127.0.0.1:3307/action?useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&zeroDateTimeBehavior=round&autoReconnect=true
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  zipkin:
    base-url: http://localhost:9411
    service:
      name: ${spring.application.name}
  sleuth:
    #监控开关
    enabled: true
    #采样率
    sampler:
      percentage: 1

#create：每次加载hibernate时都会删除上一次的生成的表，然后根据你的model类再重新来生成新表，哪怕两次没有任何改变也要这样执行，这就是导致数据库表数据丢失的一个重要原因。
#create-drop：每次加载hibernate时根据model类生成表，但是sessionFactory一关闭,表就自动删除。
#update：最常用的属性，第一次加载hibernate时根据model类会自动建立起表的结构（前提是先建立好数据库），以后加载hibernate时根据model类自动更新表结构，即使表结构改变了但表中的行仍然存在不会删除以前的行。要注意的是当部署到服务器后，表结构是不会被马上建立起来的，是要等应用第一次运行起来后才会。
#validate：每次加载hibernate时，验证创建数据库表结构，只会和数据库中的表进行比较，不会创建新表，但是会插入新值。
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

  #thymeleaf配置
  thymeleaf:
      cache: false
      prefix: classpath:/templates/
      check-template-location: true
      suffix: .html
      encoding: UTF-8
      content-type: text/html
      mode: LEGACYHTML5

  #json配置
  jackson:
      time-zone: Asia/Chongqing
      date-format: yyyy-MM-dd HH:mm:ss
      joda-date-time-format: yyyy-MM-dd HH:mm:ss


  #activemq配置
  activemq:
    broker-url: tcp://localhost:61616
    in-memory: true
    #如果此处设置为true，需要加如下的依赖包，否则会自动配置失败，报JmsMessagingTemplate注入失败
    pool:
      enabled: true


#actuator 中/beans访问需要的配置
management:
  security:
    enabled: false
  #actuator 中/beans访问统一加上/beans，以方便权限管理配置
  context-path: /mgmt

#允许远程关闭服务 curl -X POST http://localhost:8080/shutdown
endpoints:
  shutdown:
    enabled: true

